spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: dbtmdgh9@gmail.com
    password: zopkhnajhcidygom
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          timeout: 5000

  datasource:
    master:
      jdbc-url: jdbc:mariadb://192.168.235.27:3306/ysh
      driver-class-name: org.mariadb.jdbc.Driver
      username: ysh
      password: qwer1234
    slave:
      jdbc-url: jdbc:mariadb://192.168.235.31:3306/ysh
      driver-class-name: org.mariadb.jdbc.Driver
      username: ysh
      password: qwer1234
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace